language: ruby
rvm:
 - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
script: bundle exec rspec
